SELECT TIPO, COUNT(TIPO)
FROM EQUIPOS JOIN SALON_EQUIPOS USING(ID_EQUIPO)
WHERE ID_SALON = 'TLC-1'
GROUP BY TIPO;


SELECT * FROM RESPONSABLES
WHERE ID_RESPONSABLE = ?
AND PASSWORD = ?;

SELECT * FROM RESERVACIONES
WHERE SALON = 'B-5'
AND STATUS = 'Pendiente'
AND (
  (FECHA = '2024-12-04')
  AND (
    (HORARIO_ENTRADA < '19:00:00' AND HORARIO_SALIDA > '17:00:00'))
);


SELECT ID_RESERVACION, SALON, NOMBRE, FECHA, HORARIO_ENTRADA,
        HORARIO_SALIDA, ASUNTO, STATUS 
FROM RESERVACIONES re JOIN SALONES sa ON sa.ID_SALON = re.SALON 
JOIN EDIFICIOS USING(ID_EDIFICIO)
WHERE ID_RESPONSABLE = 'L21280548';